### PR TITLE
Quote parameters to pandoc

### PR DESCRIPTION
**Pull request by bersace**
Fixes passing arguments with space like beamer option "notes on second screen".

### CODE REVIEW

**Comment by bersace** [comment]
Cf. https://github.com/Pythonity/icon-font-to-png/issues/10

**Comment by daamien** [comment]
`pandoc-latex-tip` is an interesting pandoc filter but AFAIK it is not used at the moment in our document production chains. We might as well remove it and avoid all the pillow/fontawesome trickery....

**Comment by bersace** [comment]
@daamien pourquoi l'installe-t-on alors ?

**Comment by daamien** [comment]
@bersace : 

TL;DR : Good idea, Bad execution 

During the early development stages of the dalidoc3 toolchain, I was optimistic and I tried to add as many cool features as possible. The `pandoc-latex-tip` is a nice thing to have but in practice its a bit redundant with `pandoc-latex-environment` and I failed to promote the additional syntax it required and never convinced anyone to use actually it....

I have kept it in the pandocker machine until then because I  still had the secret hope to push it again at some point. But really if it creates problems in itself, I think we should get rid of it.

**Pull request merged**
