### PR TITLE
Switch to buster

### LINKED ISSUE #99: Prepare for Buster

### PR DESCRIPTION
**Pull request by daamien**
DO NOT MERGE until  buster is officially stable

Closes #99

### CODE REVIEW

**Comment by daamien** [comment]
I hate texlive so much
https://tex.stackexchange.com/questions/429714/tlmgr-remote-repository-is-newer-than-local-2017-2018

**Comment by agusmba** [comment]
I have included TinyTex into my pandoc docker image without too much hassle. Just in case you want to look at alternatives.

**Comment by daamien** [comment]
Interesting comment:

https://github.com/dalibo/pandocker/issues/122#issuecomment-565201945

**Comment by daamien** [comment]
The texlive issue seems to be fixed with buster \o/

However there's a remaining bug with the `xelatexemoji` package. 

Maybe switching to : https://github.com/alecjacobson/coloremoji.sty

Or drop the support and tell people to use the noto font : https://www.google.com/get/noto/help/emoji/

**Pull request closed without merging**
