### PR TITLE
Adds pandoc-crossref at 0.3.6.0, latest for Pandoc 2.9

### LINKED ISSUE #122: Include pandoc-crossref
**Is your feature request related to a problem? Please describe.**

My build uses pandoc-crossref, which I've installed locally. It's not available in pandocker.

**Describe the solution you'd like**

pandoc-crossref could be included in pandocker.

**Describe alternatives you've considered**

I could build and ship my own fork.

**Additional context**

https://github.com/lierdakil/pandoc-crossref

### PR DESCRIPTION
**Pull request by colindean**
Fixes #122

Combined with #125, this builds my document that needs both `pandoc-citeproc` and `pandoc-crossref`!

### CODE REVIEW

**Comment by colindean** [comment]
Blah, new commit upgraded to pandoc 2.9, need to get pandoc-crossref 0.3.6.0 for that…

The one frustrating thing about pandoc-crossref is that its binary releases are for a specific version of pandoc. That is:

* 0.3.6.0 supports only pandoc 2.9 
* 0.3.5.0 supports only pandoc 2.8

So it has to be upgraded when pandoc is upgraded.

**Comment by colindean** [comment]
> it has to be upgraded when pandoc is upgraded.

Should I write some tool that can divine the correct pandoc-crossref version based on the `${PANDOC_VERSION}`?

**Comment by daamien** [comment]
Thanks for this patch !

No don't bother guessing the PANDOC_VERSION, just add a comment near the PANDOC_VERSION variable saying that the crossref version must match the pandoc version

**Comment by colindean** [comment]
Added the comment!

**Comment by daamien** [comment]
Great !

thanks a lot

**Pull request merged**
