### PR TITLE
switch to buster, use texlive-fonts-extra instead of tlmgr

### PR DESCRIPTION
**Pull request by daamien**

### CODE REVIEW

**Comment by daamien** [comment]
@colindean: [Thanks for the tip] ! It works if we install the fonts with the `texlive-fonts-extra` package instead of `tlmgr install`. There's a remaining bug with emoji support but that's another story...

[Thanks for the tip]: https://github.com/dalibo/pandocker/issues/122#issuecomment-565201945
 
However, just like you said, the `texlive-fonts-extra` package and its dependencies are just insanely big. The regular buster image is 1.1GB. The buster-with-texlive-fonts-extra is 2.15GB. I am bit reluctant to waste that much disk space just because  the texlive community is not able to offer a proper repository that would work with debian buster. The whole point of this image is to produce the tyniest  tiny docker image in order to save space on my colleagues computers and  so that they can avoid installing the `texlive-full` horror...

So I need to talk about this with them and see what we decide...

**Comment by colindean** [comment]
If the large download is acceptable at build time, what you could do is use the package and then _delete_ the fonts you don't want to include. set up a list in the darker file that is an allow list and delete everything else that the package installs.

**Comment by colindean** [comment]
```
GREP=ggrep #on a mac, so I'm using gnu grep from Homebrew symlinked to ggrep
curl https://packages.debian.org/buster/all/texlive-fonts-extra/filelist | grep 'texlive/' > contents
$GREP -P "(ly1|inconsolata|sourcesanspro|sourcecodepro|mweights|noto)/" contents
```

That _seems_ to be OK. Reverse that with `-v` and delete anything in the list, e.g. `grep -Pv $PATTERN | xargs rm -f`. 

It'd be better to [install and use `apt-list`](https://askubuntu.com/a/32509) instead of curling that URL, though.

**Comment by daamien** [comment]
@colindean : Somehow while we were discussing this, the tlmgr bug silently disappeared and I've been able to build a buster image without `texlive-fonts-extra`. 

The image is available using the  `buster`

```
docker pull dalibo/pandocker:buster
```

There is still the one issue with emojis but all the rest should work. 

If that's ok for you, I am going to close this Merge Request

**Comment by colindean** [comment]
Yeah, if it works now for some reason, close this and ship it!

**Comment by colindean** [comment]
I built the `buster` myself to see what changed. Looks like TeXLive changed something:

```
Step 25/32 : RUN tlmgr init-usertree &&     tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/ &&     tlmgr install ly1 inconsolata sourcesanspro sourcecodepro mweights noto ||     tlmgr install ly1 inconsolata sourcesanspro sourcecodepro mweights noto
 ---> Running in 580ede3b226f
(running on Debian, switching to user mode!)
tlmgr: setting default package repository to http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/
(running on Debian, switching to user mode!)
TeX Live 2018 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/ (not verified: gpg unavailable)
[1/6, ??:??/??:??] install: inconsolata [316k]
[2/6, 00:03/08:55] install: ly1 [54k]
[3/6, 00:04/10:10] install: mweights [2k]
[4/6, 00:05/12:40] install: noto [49291k]
[5/6, 05:45/06:31] install: sourcecodepro [3278k]
[6/6, 06:10/06:33] install: sourcesanspro [3383k]
running mktexlsr ...
done running mktexlsr.
running updmap ...
tlmgr: updmap failed (status 1), output:
updmap [ERROR]: Either -sys or -user mode is required.
updmap [ERROR]: In nearly all cases you should use updmap -sys.
updmap [ERROR]: For special cases see http://tug.org/texlive/scripts-sys-user.html

tlmgr: An error has occurred. See above messages. Exiting.

tlmgr: package log updated: /root/texmf/web2c/tlmgr.log
(running on Debian, switching to user mode!)
TeX Live 2018 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/ (not verified: gpg unavailable)
tlmgr install: package already present: inconsolata
tlmgr install: package already present: ly1
tlmgr install: package already present: mweights
tlmgr install: package already present: noto
tlmgr install: package already present: sourcecodepro
tlmgr install: package already present: sourcesanspro
Removing intermediate container 580ede3b226f
```

It's a little disconcerting and I don't know the TeXLive ecosystem well-enough to understand what could have changed in the last few days, but hey, if it works and it's secure, ship it.

**Comment by daamien** [comment]
Great ! Thanks for the feedback

**Pull request closed without merging**
